### PR TITLE
Fix path separator for Windows

### PR DESCRIPTION
**Pull request by tamago324**
The Windows path separator was `;`, which was fixed.

Thank you.

### CODE REVIEW

**Comment by petobens** [comment]
Thank you! Can write everything in the same ternary operatory? Something like
```viml
let $PATH = venv_dir . (has('win32')? '/Scripts;': '/bin:')  . $PATH
```

**Comment by petobens** [comment]
Out of curiosity: does poet-v work ok on windows? Are you using pipenv or poetry?

**Comment by tamago324** [comment]
> Thank you! Can write everything in the same ternary operatory? Something like
> 
> ```viml
> let $PATH = venv_dir . (has('win32')? '/Scripts;': '/bin:')  . $PATH
> ```

Thank you for the review.

**Comment by tamago324** [comment]
> Out of curiosity: does poet-v work ok on windows? Are you using pipenv or poetry?

poet-v works correctly on Windows.
I also use poetry.

**Comment by petobens** [comment]
Thank you once again

**Comment by tamago324** [comment]
Thank you!
However, when I tried it again, the behavior was wrong, so I created another issue.

**Pull request merged**
