### PR TITLE
Fix Python 3.5 compatibility for pathlib

### PR DESCRIPTION
**Pull request by leoluyi**
Fix `Path` object in `shutil`

### CODE REVIEW

**Comment by petobens** [comment]
Won't this break on windows?
```python
from pathlib import Path, PureWindowsPath

l = Path('/home/pedro/')
w = PureWindowsPath('c:\\windows')
print(str(l)) # /home/pedro
print(str(w)) # c:\window
print(l.as_posix()) # /home/pedro
print(w.as_posix()) # c:/windows
```

**Comment by petobens** [comment]
@tamago324 can you try this out?

**Comment by tamago324** [comment]
> @tamago324 can you try this out?

@petobens Yes. I'll give it a try!

**Comment by tamago324** [comment]
@petobens I was able to confirm that it worked fine on Windows.

**Comment by petobens** [comment]
@tamago324 thanks! Merging

**Comment by tamago324** [comment]
@petobens Thank you so much!

**Pull request merged**
